# Generated by Django 4.2.14 on 2024-08-05 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_article_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
