# Generated by Django 4.2.14 on 2024-08-10 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_delete_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='portfolio/images/')),
                ('title', models.CharField(max_length=23)),
                ('url', models.URLField(blank=True)),
                ('description', models.CharField(max_length=250)),
            ],
        ),
    ]
